secretGenerator:
- name: mysql-pass
  literals:
  - password=changeme
configMapGenerator:
- name: mysql-initdb
  files:
  - mysql/docker-entrypoint-initdb.d/initdb.sql
resources:
  - mysql/deployment.yaml
  - mysql/service.yaml
  - mysql/pv-volume.yaml
  - mysql/pv-claim.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
