apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
      tier: frontend
  template:
    metadata:
      labels:
        app: blog
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: tkak/cakephp-buildpacks-demo
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
          - name: PORT
            value: "8080"
          - name: BLOG_DB_HOST
            value: mysql
          - name: BLOG_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
