apiVersion: v1
kind: Service
metadata:
  name: blog
  labels:
    app: blog
spec:
  selector:
    app: blog
    tier: frontend
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
